apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: apache7-service
  name: apache7-service
spec:
  type: LoadBalancer
  ports:
    - name: "8008"
      port: 8008
      targetPort: 80
  selector:
    io.kompose.service: apache7-service
