apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql-service
  name: mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql-service
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:8.1
          name: mysql-container-laravel11
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-service-claim0
            - mountPath: /mnt
              name: mysql-service-claim1
      restartPolicy: Always
      volumes:
        - name: mysql-service-claim0
          persistentVolumeClaim:
            claimName: mysql-service-claim0
        - name: mysql-service-claim1
          persistentVolumeClaim:
            claimName: mysql-service-claim1
